# Generated by Django 3.1.7 on 2021-03-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
